# Inlcude _pages
include: ["_pages"]

# Exclude _webpack from jekyll watching
exclude: ["_webpack"]

# No dates in URL's
permalink: /:title/

# Where all of your Markup and HTML files are. (Assets like JS and SCSS are handeled by Webpack)
source: src

# Where your compiled files will be outputted to.
destination: dist

# Setting our sass directory.
sass:
  load_paths:
    - assets/css
  # style: compressed

# bind to all IPs, rather than just to localhost
host: 127.0.0.1

# Default variables, you can overwrite them in posts or pages frontmatter
title: The Page Title
ogimage: urltosuperfancyimage.jpg
description: The page description

# Editor config options for Cloudcannon
_options:
  content:
    styles: /src/assets/css/wysiwyg.css
    bold: true
    italic: true
    link: true
    numeredlist: true
    bulletlist: true
